export const paths = {
  home: "/",
  about: "/about-us",
  portfolio: "/portfolio",
  presentation: "/presentation",
  services: "/services",
  faq: "/faq",
  blog: "/blog",
  contacts: "/#contacts",
  support: "/#contacts",
  documents: "/documents",
  stages: "/about-us/#stages",
  stock: "/sales",
  policy: "/policy",
  whyWe: "/about-us#why-we",
  reviews: "/#reviews",
  comand: "/#comand",
};
